/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.caso;

import dao.CasoDAO;
import dao.DispositivoDAO;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import model.Caso;
import model.Dispositivo;
import model.TipoAcesso;
import model.Usuario;
import model.gerenciatela.GerenciaTelaCaso;
import model.table.TabelaModeloCaso;
import util.ConversorData;
import view.dispositivo.TelaDispositivoImportaBanco;
//import view.dispositivo.TelaNovoDispositivo;
import view.dispositivo.TelaPrincipalDispositivo;
import view.usuario.TelaAlterarUsuario;

/**
 *
 * @author BRUNA
 */
public class TelaPrincipalCaso extends javax.swing.JFrame {
    private final Usuario usuarioLogado;
    private Dispositivo dispositivoSelecionado;
    private Caso casoSelecionado;
    private List<Caso> casos;
    private List<Caso> casosCompartilhados;
    private List<Dispositivo> dispositivos;
    
    /**
     * Creates new form TelaPrincipalCaso
     * @param usuario
     */
    public TelaPrincipalCaso(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        this.setExtendedState(MAXIMIZED_BOTH);
        arvoreDispositivos.setVisible(false);
        
        gerenciaTela();
        preenchePainelInferior();
        preencheTabelasCasos("TUDO");
        configuraJTable();
    }
    
    
    private void configuraJTable(){
        tabelaMeusCasos.setFont(new Font("Tahoma", Font.PLAIN, 14));
        tabelaMeusCasos.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        tabelaMeusCasos.getTableHeader().setForeground(new Color(255,149,40));
        tabelaMeusCasos.setRowHeight(25);
        tabelaCasosCompartilhados.setFont(new Font("Tahoma", Font.PLAIN, 14));
        tabelaCasosCompartilhados.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        tabelaCasosCompartilhados.getTableHeader().setForeground(new Color(255,149,40));
        tabelaCasosCompartilhados.setRowHeight(25);
    }

    
    private void gerenciaTela() {
        GerenciaTelaCaso gt = new GerenciaTelaCaso();
        this.setSize(gt.getFramePrincipalCaso());
        painelCasos.setPreferredSize(gt.getPainelCasos());
        painelCasosCompartilhados.setPreferredSize(gt.getPainelCasos());
        painelDispositivos.setPreferredSize(gt.getPainelDispositivos());
        painelInferior.setPreferredSize(gt.getPainelInferior());
        scrollPaneTabelaCasos.setPreferredSize(gt.getTabelaCasos());
        scrollPaneTabelaCasosCompartilhados.setPreferredSize(gt.getTabelaCasos());
        scrollPaneArvoreDispositivos.setPreferredSize(gt.getArvoreDispositivos());
    }
    
    
    private void ativaBotoesPainelDispositivo(){
        botaoAbrir.setEnabled(true);
        botaoNovo.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDispositivos = new javax.swing.JPanel();
        scrollPaneArvoreDispositivos = new javax.swing.JScrollPane();
        arvoreDispositivos = new javax.swing.JTree();
        botaoAbrir = new javax.swing.JButton();
        botaoNovo = new javax.swing.JButton();
        painelInferior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelCasos = new javax.swing.JPanel();
        scrollPaneTabelaCasos = new javax.swing.JScrollPane();
        tabelaMeusCasos = new javax.swing.JTable();
        painelCasosCompartilhados = new javax.swing.JPanel();
        scrollPaneTabelaCasosCompartilhados = new javax.swing.JScrollPane();
        tabelaCasosCompartilhados = new javax.swing.JTable();
        painelBotoes = new javax.swing.JPanel();
        botaoExcluirCaso = new javax.swing.JButton();
        botaoNovoCaso = new javax.swing.JButton();
        botaoAlterarCaso = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        campoPesquisaCaso = new javax.swing.JTextField();
        botaoPesquisaCaso = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConfigurar = new javax.swing.JMenu();
        botaoAlterarDadosUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTA DE CASOS");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        painelDispositivos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DISPOSITIVOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(24, 62, 81))); // NOI18N

        scrollPaneArvoreDispositivos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        arvoreDispositivos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        arvoreDispositivos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arvoreDispositivosValueChanged(evt);
            }
        });
        scrollPaneArvoreDispositivos.setViewportView(arvoreDispositivos);

        botaoAbrir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/abrir.png"))); // NOI18N
        botaoAbrir.setText("ABRIR");
        botaoAbrir.setEnabled(false);
        botaoAbrir.setPreferredSize(new java.awt.Dimension(81, 30));
        botaoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbrirActionPerformed(evt);
            }
        });

        botaoNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        botaoNovo.setText("NOVO");
        botaoNovo.setEnabled(false);
        botaoNovo.setPreferredSize(new java.awt.Dimension(81, 30));
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDispositivosLayout = new javax.swing.GroupLayout(painelDispositivos);
        painelDispositivos.setLayout(painelDispositivosLayout);
        painelDispositivosLayout.setHorizontalGroup(
            painelDispositivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDispositivosLayout.createSequentialGroup()
                .addGroup(painelDispositivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDispositivosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(scrollPaneArvoreDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDispositivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelDispositivosLayout.setVerticalGroup(
            painelDispositivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDispositivosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(scrollPaneArvoreDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDispositivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("USUÁRIO:");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelUsuario.setText("usuario");

        labelData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelData.setText("HOJE:");

        javax.swing.GroupLayout painelInferiorLayout = new javax.swing.GroupLayout(painelInferior);
        painelInferior.setLayout(painelInferiorLayout);
        painelInferiorLayout.setHorizontalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInferiorLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelData)
                .addContainerGap())
        );
        painelInferiorLayout.setVerticalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelUsuario)
                    .addComponent(labelData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setForeground(new java.awt.Color(24, 62, 81));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        scrollPaneTabelaCasos.setBackground(new java.awt.Color(255, 255, 255));

        tabelaMeusCasos.setForeground(new java.awt.Color(51, 51, 51));
        tabelaMeusCasos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaMeusCasos.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaMeusCasos.setSelectionBackground(new java.awt.Color(40, 101, 132));
        tabelaMeusCasos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaMeusCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMeusCasosMouseClicked(evt);
            }
        });
        scrollPaneTabelaCasos.setViewportView(tabelaMeusCasos);

        painelCasos.add(scrollPaneTabelaCasos);

        jTabbedPane1.addTab("MEUS CASOS", null, painelCasos, "");

        scrollPaneTabelaCasosCompartilhados.setBackground(new java.awt.Color(255, 255, 255));

        tabelaCasosCompartilhados.setForeground(new java.awt.Color(51, 51, 51));
        tabelaCasosCompartilhados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaCasosCompartilhados.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaCasosCompartilhados.setSelectionBackground(new java.awt.Color(40, 101, 132));
        tabelaCasosCompartilhados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaCasosCompartilhados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCasosCompartilhadosMouseClicked(evt);
            }
        });
        scrollPaneTabelaCasosCompartilhados.setViewportView(tabelaCasosCompartilhados);

        painelCasosCompartilhados.add(scrollPaneTabelaCasosCompartilhados);

        jTabbedPane1.addTab("CASOS COMPARTILHADOS", painelCasosCompartilhados);

        botaoExcluirCaso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoExcluirCaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sair.png"))); // NOI18N
        botaoExcluirCaso.setText("Excluir");
        botaoExcluirCaso.setToolTipText("Selecione um caso para excluir");
        botaoExcluirCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirCasoActionPerformed(evt);
            }
        });

        botaoNovoCaso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoNovoCaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        botaoNovoCaso.setText("NOVO");
        botaoNovoCaso.setToolTipText("Clique para criar um novo caso");
        botaoNovoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoCasoActionPerformed(evt);
            }
        });

        botaoAlterarCaso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoAlterarCaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gerar.png"))); // NOI18N
        botaoAlterarCaso.setText("ALTERAR");
        botaoAlterarCaso.setToolTipText("Selecione um caso para alterar");
        botaoAlterarCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarCasoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(botaoNovoCaso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAlterarCaso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluirCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoNovoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterarCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluirCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoPesquisaCaso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        botaoPesquisaCaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pesquisar.png"))); // NOI18N
        botaoPesquisaCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaCasoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoPesquisaCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoPesquisaCaso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPesquisaCaso)
                    .addComponent(botaoPesquisaCaso, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        menuConfigurar.setText("Configurar");

        botaoAlterarDadosUsuario.setText("Alterar Dados");
        botaoAlterarDadosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarDadosUsuarioActionPerformed(evt);
            }
        });
        menuConfigurar.add(botaoAlterarDadosUsuario);

        jMenuBar1.add(menuConfigurar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1))
                .addGap(77, 77, 77)
                .addComponent(painelDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
            .addComponent(painelInferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1))
                    .addComponent(painelDispositivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbrirActionPerformed
        if(dispositivoSelecionado == null){
            JOptionPane.showMessageDialog(this, "Selecione um dispositivo!");
        }
        else{
            DispositivoDAO dispositivoDAO = new DispositivoDAO();
            
            if(dispositivoDAO.verificaImportacaoDispositivo(dispositivoSelecionado.getTabelaContato()) > 0){
                //new TelaPrincipalDispositivo(this, false, dispositivoSelecionado).setVisible(true);
                new TelaPrincipalDispositivo(dispositivoSelecionado).setVisible(true);
                this.dispose();
            }
            else{
                new TelaDispositivoImportaBanco(dispositivoSelecionado).setVisible(true);
            }
        }
    }//GEN-LAST:event_botaoAbrirActionPerformed

    private void arvoreDispositivosValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arvoreDispositivosValueChanged
        if(!evt.getPath().getLastPathComponent().toString().equals(casoSelecionado.getDescricao())
            && !evt.getPath().getLastPathComponent().toString().equals("Sem dispositivos")){
            DispositivoDAO dispositivoDAO = new DispositivoDAO();
            dispositivoSelecionado = dispositivoDAO.pesquisaDispositivoPorNome(evt.getPath().getLastPathComponent().toString(), casoSelecionado);
        }
    }//GEN-LAST:event_arvoreDispositivosValueChanged

    private void tabelaMeusCasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMeusCasosMouseClicked
        if(evt.getClickCount() > 0){
            this.casoSelecionado = casos.get(tabelaMeusCasos.getSelectedRow());
            carregaListaDispositivos();
            carregaJTreeDispositivos();
            arvoreDispositivos.setVisible(true);
            ativaBotoesPainelDispositivo();
        }
    }//GEN-LAST:event_tabelaMeusCasosMouseClicked

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        if(casoSelecionado == null){
            JOptionPane.showMessageDialog(this, "É necessário selecionar um caso!");
        }
        else{
            //new TelaNovoDispositivo(this, true, casoSelecionado).setVisible(true);
        }
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void tabelaCasosCompartilhadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCasosCompartilhadosMouseClicked
        if(evt.getClickCount() > 0){
            this.casoSelecionado = casos.get(tabelaCasosCompartilhados.getSelectedRow());
            carregaListaDispositivos();
            carregaJTreeDispositivos();
            arvoreDispositivos.setVisible(true);
            ativaBotoesPainelDispositivo();
        }
    }//GEN-LAST:event_tabelaCasosCompartilhadosMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        preencheTabelasCasos("TUDO");
    }//GEN-LAST:event_formWindowGainedFocus

    private void botaoAlterarDadosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarDadosUsuarioActionPerformed
        new TelaAlterarUsuario(this, true, usuarioLogado).setVisible(true);
    }//GEN-LAST:event_botaoAlterarDadosUsuarioActionPerformed

    private void botaoNovoCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoCasoActionPerformed
        new TelaNovoCaso(this, true, usuarioLogado).setVisible(true);
    }//GEN-LAST:event_botaoNovoCasoActionPerformed

    private void botaoAlterarCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarCasoActionPerformed
        if(casoSelecionado == null){
            JOptionPane.showMessageDialog(this, "Selecione um caso!");
        }
        else{
            new TelaAlterarCaso(this, true, casoSelecionado, usuarioLogado).setVisible(true);
        }
    }//GEN-LAST:event_botaoAlterarCasoActionPerformed

    private void botaoExcluirCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirCasoActionPerformed
        if(casoSelecionado == null){
            JOptionPane.showMessageDialog(this, "Selecione um caso!");
        }
        else{
            int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o caso: "+casoSelecionado.getDescricao(), "EXCLUIR CASO", JOptionPane.YES_NO_OPTION);
            
            if(resposta == 0){
                DispositivoDAO dispositivoDAO = new DispositivoDAO();
                List<Dispositivo> dispositivosExcluir = dispositivoDAO.dispositivosPorCaso(casoSelecionado);
                
                for(Dispositivo dispositivo : dispositivosExcluir){
                    dispositivoDAO.excluir(dispositivo);
                    File file = new File(dispositivo.getDiretorio());
                    file.delete();
                }
                
                CasoDAO casoDAO = new CasoDAO();
                if(casoDAO.excluir(casoSelecionado)){
                    File file = new File(casoSelecionado.getDiretorio());
                    file.delete();
                    
                    casoSelecionado = null;  
                    JOptionPane.showMessageDialog(this, "Caso excluído!");
                }
            }
        }
    }//GEN-LAST:event_botaoExcluirCasoActionPerformed

    private void botaoPesquisaCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaCasoActionPerformed
        preencheTabelasCasos("NOME");
    }//GEN-LAST:event_botaoPesquisaCasoActionPerformed

    
    private void preenchePainelInferior(){
        labelUsuario.setText(usuarioLogado.getNome());
        labelData.setText("HOJE: "+ConversorData.getStringDataAtual());
    }
    
    
    private void carregaJTreeDispositivos(){
        DefaultMutableTreeNode titulo = new DefaultMutableTreeNode(casoSelecionado.getDescricao());

        if(dispositivos.isEmpty()){
            DefaultMutableTreeNode dispositivo[] = new DefaultMutableTreeNode[1];
            dispositivo[0] = new DefaultMutableTreeNode("Sem dispositivos");
            titulo.add(dispositivo[0]);
        }
        else{
            for (int i = 0; i < dispositivos.size(); i++) {
                DefaultMutableTreeNode dispositivo[] = new DefaultMutableTreeNode[dispositivos.size()];
                dispositivo[i] = new DefaultMutableTreeNode(dispositivos.get(i));
                titulo.add(dispositivo[i]);
            }
        }
        
        arvoreDispositivos.setModel(new DefaultTreeModel(titulo));
    }
    
    
    private void preencheTabelasCasos(String filtro){
        CasoDAO casoDAO = new CasoDAO();
        if(filtro.equals("TUDO")){
            casos = casoDAO.pesquisaListaCasos(usuarioLogado, TipoAcesso.Criador);
            casosCompartilhados = casoDAO.pesquisaListaCasos(usuarioLogado, TipoAcesso.Visualizar);
        }
        if(filtro.equals("NOME")){
            casos = casoDAO.pesquisaListaCasosPorNome(usuarioLogado, TipoAcesso.Criador, campoPesquisaCaso.getText());
            casosCompartilhados = casoDAO.pesquisaListaCasosPorNome(usuarioLogado, TipoAcesso.Visualizar, campoPesquisaCaso.getText()); 
        }
        tabelaMeusCasos.setModel(new TabelaModeloCaso(casos));
        tabelaCasosCompartilhados.setModel(new TabelaModeloCaso(casosCompartilhados));
    }
    
    
    private void carregaListaDispositivos(){
        DispositivoDAO dispositivoDAO = new DispositivoDAO();
        dispositivos = dispositivoDAO.dispositivosPorCaso(casoSelecionado);
    }
    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalCaso().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arvoreDispositivos;
    private javax.swing.JButton botaoAbrir;
    private javax.swing.JButton botaoAlterarCaso;
    private javax.swing.JMenuItem botaoAlterarDadosUsuario;
    private javax.swing.JButton botaoExcluirCaso;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoNovoCaso;
    private javax.swing.JButton botaoPesquisaCaso;
    private javax.swing.JTextField campoPesquisaCaso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JMenu menuConfigurar;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCasos;
    private javax.swing.JPanel painelCasosCompartilhados;
    private javax.swing.JPanel painelDispositivos;
    private javax.swing.JPanel painelInferior;
    private javax.swing.JScrollPane scrollPaneArvoreDispositivos;
    private javax.swing.JScrollPane scrollPaneTabelaCasos;
    private javax.swing.JScrollPane scrollPaneTabelaCasosCompartilhados;
    private javax.swing.JTable tabelaCasosCompartilhados;
    private javax.swing.JTable tabelaMeusCasos;
    // End of variables declaration//GEN-END:variables
}
